global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yaml

scrape_configs:
  - job_name: "rails_app"
    static_configs:
      - targets: ["prometheus_exporter:9394"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis_exporter:9121"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres_exporter:9187"]